#include <vector>
const double Ab = 415.04;
const double A = 440;
const double B = 466.16;
const double H = 493.62;
const double C = 523.38;
const double Db = 553.89;
const double D = 587.46;
const double Eb = 622.56;
const double E = 659.18;
const double F = 698.85;
const double Gb = 740.05;
const double G = 784.30;
const double AUD_TONE_RING_FREQ_Ab = Ab;
const double AUD_TONE_RING_FREQ_A = A;
const double AUD_TONE_RING_FREQ_B = B;
const double AUD_TONE_RING_FREQ_H = H;
const double AUD_TONE_RING_FREQ_C = C;
const double AUD_TONE_RING_FREQ_Db = Db;
const double AUD_TONE_RING_FREQ_D = D;
const double AUD_TONE_RING_FREQ_Eb = Eb;
const double AUD_TONE_RING_FREQ_E = E;
const double AUD_TONE_RING_FREQ_F = F;
const double AUD_TONE_RING_FREQ_Gb = Gb;
const double AUD_TONE_RING_FREQ_G = G;
const double AUD_TONE_RING_FREQ_A2b = Ab * 2;
const double AUD_TONE_RING_FREQ_A2 = A * 2;
const double AUD_TONE_RING_FREQ_B2 = B * 2;
const double AUD_TONE_RING_FREQ_H2 = H * 2;
const double AUD_TONE_RING_FREQ_C2 = C * 2;
const double AUD_TONE_RING_FREQ_D2b = Db * 2;
const double AUD_TONE_RING_FREQ_D2 = D * 2;
const double AUD_TONE_RING_FREQ_E2b = Eb * 2;
const double AUD_TONE_RING_FREQ_E2 = E * 2;
const double AUD_TONE_RING_FREQ_F2 = F * 2;
const double AUD_TONE_RING_FREQ_G2b = Gb * 2;
const double AUD_TONE_RING_FREQ_G2 = G * 2;
const double AUD_TONE_RING_FREQ_A3b = Ab * 4;
const double AUD_TONE_RING_FREQ_A3 = A * 4;
const double AUD_TONE_RING_FREQ_B3 = B * 4;
const double AUD_TONE_RING_FREQ_H3 = H * 4;
const double AUD_TONE_RING_FREQ_C3 = C * 4;
const double AUD_TONE_RING_FREQ_D3b = Db * 4;
const double AUD_TONE_RING_FREQ_D3 = D * 4;
const double AUD_TONE_RING_FREQ_E3b = Eb * 4;
const double AUD_TONE_RING_FREQ_E3 = E * 4;
const double AUD_TONE_RING_FREQ_F3 = F * 4;
const double AUD_TONE_RING_FREQ_G3b = Gb * 4;
const double AUD_TONE_RING_FREQ_G3 = G * 4;
const double AUD_TONE_RING_FREQ_A4b = Ab * 8;
const double AUD_TONE_RING_FREQ_A4 = A * 8;
const double AUD_TONE_RING_FREQ_B4 = B * 8;
const double AUD_TONE_RING_FREQ_H4 = H * 8;
const double AUD_TONE_RING_FREQ_C4 = C * 8;
const double AUD_TONE_FREQ_OFF = 0;
const double AUD_TONE_RING_FREQ_UNK = 0;

typedef struct {
    double frequency; // Tone frequency
    int duration;     // Duration in milliseconds
} ToneData;
void PlayToneSequence(std::vector<ToneData> seq);