//(C) 2024 HMD Global. All rights reserved.
//Composed by Markus Castren

#ifdef RINGDATA_INCLUDE_SEQUENCIES
const std::vector<ToneData> ring_ringing2_seq = {
        /*Tempo: 800bpm*/        
        {AUD_TONE_RING_FREQ_E2, TONE_TIME_IN_MS(17)},
        {AUD_TONE_RING_FREQ_E2, TONE_TIME_IN_MS(17)},
        {AUD_TONE_RING_FREQ_E2, TONE_TIME_IN_MS(37)},
        {AUD_TONE_RING_FREQ_D2, TONE_TIME_IN_MS(75)},
        {AUD_TONE_RING_FREQ_E2, TONE_TIME_IN_MS(75)},
        {AUD_TONE_RING_FREQ_D2, TONE_TIME_IN_MS(75)},
        {AUD_TONE_RING_FREQ_E2, TONE_TIME_IN_MS(75)},
        {AUD_TONE_RING_FREQ_D2, TONE_TIME_IN_MS(75)},
        {AUD_TONE_RING_FREQ_E2, TONE_TIME_IN_MS(75)},
        {AUD_TONE_RING_FREQ_D2, TONE_TIME_IN_MS(75)},
        {AUD_TONE_RING_FREQ_E2, TONE_TIME_IN_MS(65)},
        {AUD_TONE_RING_FREQ_E2, TONE_TIME_IN_MS(8)},
        {AUD_TONE_RING_FREQ_D2, TONE_TIME_IN_MS(75)},
        {AUD_TONE_RING_FREQ_E2, TONE_TIME_IN_MS(75)},
        {AUD_TONE_RING_FREQ_D2, TONE_TIME_IN_MS(75)},
        {AUD_TONE_RING_FREQ_E2, TONE_TIME_IN_MS(8)},
        {AUD_TONE_RING_FREQ_E2, TONE_TIME_IN_MS(65)},
        {AUD_TONE_RING_FREQ_D2, TONE_TIME_IN_MS(36)},
        {AUD_TONE_RING_FREQ_D2, TONE_TIME_IN_MS(37)},
        {AUD_TONE_FREQ_OFF, TONE_TIME_IN_MS(164)},
        {AUD_TONE_RING_FREQ_G2, TONE_TIME_IN_MS(17)},
        {AUD_TONE_RING_FREQ_G2, TONE_TIME_IN_MS(17)},
        {AUD_TONE_RING_FREQ_G2, TONE_TIME_IN_MS(37)},
        {AUD_TONE_RING_FREQ_F2, TONE_TIME_IN_MS(75)},
        {AUD_TONE_RING_FREQ_G2, TONE_TIME_IN_MS(75)},
        {AUD_TONE_RING_FREQ_F2, TONE_TIME_IN_MS(75)},
        {AUD_TONE_RING_FREQ_G2, TONE_TIME_IN_MS(75)},
        {AUD_TONE_RING_FREQ_F2, TONE_TIME_IN_MS(75)},
        {AUD_TONE_RING_FREQ_G2, TONE_TIME_IN_MS(75)},
        {AUD_TONE_RING_FREQ_F2, TONE_TIME_IN_MS(75)},
        {AUD_TONE_FREQ_OFF, TONE_TIME_IN_MS(2)},
        {AUD_TONE_RING_FREQ_G2, TONE_TIME_IN_MS(10)},
        {AUD_TONE_FREQ_OFF, TONE_TIME_IN_MS(1)},
        {AUD_TONE_RING_FREQ_G2, TONE_TIME_IN_MS(46)},
        {AUD_TONE_RING_FREQ_G2, TONE_TIME_IN_MS(8)},
        {AUD_TONE_RING_FREQ_F2, TONE_TIME_IN_MS(75)},
        {AUD_TONE_RING_FREQ_G2, TONE_TIME_IN_MS(75)},
        {AUD_TONE_RING_FREQ_F2, TONE_TIME_IN_MS(75)},
        {AUD_TONE_RING_FREQ_G2, TONE_TIME_IN_MS(75)},
        {AUD_TONE_RING_FREQ_F2, TONE_TIME_IN_MS(75)}
};
#endif
